name: CI Build & Release (feature/*)

on:
  push:
    branches:
      - 'feature/*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./src/App/AzureKvSslExpirationChecker.csproj

      - name: Publish (Self-contained)
        run: dotnet publish ./src/App/AzureKvSslExpirationChecker.csproj -c Release -r win-x64 --self-contained true

      - name: Create ZIP
        run: |
          cd ./src/App/bin/Release/net8.0-windows/win-x64
          Rename-Item publish "EY-GDS SRE SSL-ExpiryShield"
          Compress-Archive -Path "EY-GDS SRE SSL-ExpiryShield" -DestinationPath "${{ github.workspace }}\EY-GDS SRE SSL-ExpiryShield.zip" -Force

      - name: Generate timestamp
        id: date
        run: echo "ts=$(Get-Date -UFormat '%Y%m%d%H%M%S')" >> $env:GITHUB_OUTPUT

      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag v${{ github.run_number }}.${{ steps.date.outputs.ts }}
          git push origin v${{ github.run_number }}.${{ steps.date.outputs.ts }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}.${{ steps.date.outputs.ts }}
          name: "EY-GDS SRE SSL-ExpiryShield v${{ github.run_number }}.${{ steps.date.outputs.ts }}"
          generate_release_notes: true
          files: |
            EY-GDS SRE SSL-ExpiryShield.zip
